[build]
command = "npm run build"
publish = ".next"
node_version = "18.20.8"

[build.environment]
NODE_VERSION = "18.20.8"
NPM_VERSION = "9"
NODE_ENV = "production"
NEXT_PUBLIC_BASE_URL = "https://92lottery.dev"
NEXT_PUBLIC_API_URL = "https://92lottery.dev/api"

[site]
bucket = ".next"
entry-point = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
