name = "92lottery"
compatibility_date = "2025-05-02"
main = ".vercel/output/static/_worker.js"

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18.20.8"
NPM_VERSION = "9"
NODE_ENV = "production"
NEXT_PUBLIC_BASE_URL = "https://92lottery.dev"
NEXT_PUBLIC_API_URL = "https://92lottery.dev/api"
NEXT_TELEMETRY_DISABLED = "1"

# Specify the directory where your built assets will be located
[site.build]
upload.format = "directory"
output_dir = ".vercel/output/static"

# Configure headers
[[headers]]
pattern = "/*"
[headers.cache]
cache_control = "public, max-age=86400"

[[headers]]
pattern = "/*.(js|css|svg|jpg|jpeg|png|gif|ico|woff|woff2|ttf|otf)"
[headers.cache]
cache_control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/*"
[headers.response]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
