import type { Metadata } from "next";
import "./globals.css";
import NetworkErrorHandler from "@/components/NetworkErrorHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className="flex justify-center min-h-screen items-start bg-gray-100">
        <NetworkErrorHandler>
          <div className="w-[420px] min-h-screen bg-white rounded-lg shadow-2xl relative overflow-x-hidden max-w-full">
            {children}
          </div>
        </NetworkErrorHandler>
      </body>
    </html>
  );
}
